"""
Django settings for SSAPI project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

from .db import MYSQL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
_key_env = BASE_DIR / "key.env"
if _key_env.exists():
    load_dotenv(_key_env)
else:
    load_dotenv(BASE_DIR / ".env" / "key.env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Debe coincidir con Portal-Paldaca/key.env para compartir sesion SSO.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    raise ValueError(
        "DJANGO_SECRET_KEY no definida. Copia key.env desde Portal-Paldaca "
        "(misma clave y MYSQL_*) a la raiz de ActivosPALDACA."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = ['activos.cpaldaca.com', 'www.activos.cpaldaca.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'activos',
    'core',
    'reportes',
    'usuarios',  # solo historial de migraciones; identidad en core.UsuarioPaldaca
    'mantenimientos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.PaldacaSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ErrorHandlingMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'SSAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.paldaca_urls',
            ],
        },
    },
]

WSGI_APPLICATION = 'SSAPI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = MYSQL

AUTH_USER_MODEL = "core.UsuarioPaldaca"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True

PALDACA_SSO_LOGIN_URL = os.getenv("PALDACA_SSO_LOGIN_URL", "http://localhost:5173/login/")
PALDACA_SSO_LOGOUT_URL = os.getenv(
    "PALDACA_SSO_LOGOUT_URL",
    "http://localhost:8000/api/auth/sso/logout/",
)
PALDACA_STRICT_SESSION_CONSISTENCY = os.getenv(
    "PALDACA_STRICT_SESSION_CONSISTENCY",
    "true",
)
SESSION_COOKIE_NAME = os.getenv("SESSION_COOKIE_NAME", "paldaca_sessionid")
SESSION_COOKIE_DOMAIN = os.getenv("SESSION_COOKIE_DOMAIN") or None

# SSO local: misma cookie en localhost:8000 (portal) y :8001+ (satelites).
if DEBUG:
    SESSION_COOKIE_DOMAIN = None
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_DOMAIN = None
    CSRF_COOKIE_SECURE = False
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",
        "http://localhost:8000",
        "http://localhost:8001",
        "http://localhost:8002",
    ]

LOGIN_URL = PALDACA_SSO_LOGIN_URL
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = PALDACA_SSO_LOGOUT_URL

# Configuración de manejo de errores
handler404 = 'core.views.custom_404_view'
handler500 = 'core.views.custom_500_view'
handler403 = 'core.views.custom_403_view'
handler400 = 'core.views.custom_400_view'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
