# Generated by Django 6.0.3 on 2026-06-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_activos_prefijo_mantenimiento'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mantenimiento',
            new_name='activos_man_activo__f61234_idx',
            old_name='mantenimien_activo__2809f4_idx',
        ),
        migrations.RenameIndex(
            model_name='mantenimiento',
            new_name='activos_man_estado_072fa3_idx',
            old_name='mantenimien_estado_0cfa99_idx',
        ),
    ]
