# Generated by Django 6.0.3 on 2026-06-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_activos_prefijo_tablas'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='historialmovimiento',
            new_name='activos_his_activo__580f3c_idx',
            old_name='activos_his_activo__b4a8a8_idx',
        ),
        migrations.RenameIndex(
            model_name='historialmovimiento',
            new_name='activos_his_tipo_mo_3d90a6_idx',
            old_name='activos_his_tipo_mo_07e8dc_idx',
        ),
    ]
